CREATE TABLE LOG_SUMAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    INPUT_DATA VARCHAR2(4000),
    RESULTADO_TOTAL NUMBER,
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

CREATE OR REPLACE PROCEDURE SP_INSERT_SUMAS(
    P_INPUT_DATA IN VARCHAR2,
    P_TOTAL IN NUMBER
)
AS
BEGIN
    INSERT INTO LOG_SUMAS (INPUT_DATA, RESULTADO_TOTAL)
    VALUES (P_INPUT_DATA, P_TOTAL);
END;
/

COMMIT;